name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - run: gem install rubocop
      - run: rubocop --fail-level W
      - run: ruby -c check_pve.rb

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Smoke test check_pve
        run: |
          ruby check_pve.rb --help
          ruby check_pve.rb -s 127.0.0.1 -u foo -p bar -m list-nodes || echo "Expected failure, OK"

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
