name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.0.0-p648', '2.5.9', '3.3.9']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Syntax check
        run: ruby -c check_pve.rb

      - name: Smoke test
        run: ruby check_pve.rb --help || echo "Expected failure on very old Ruby is OK"

      - name: Lint (only on Ruby >= 3)
        if: startsWith(matrix.ruby-version, '3.')
        run: |
          gem install rubocop
          rubocop --fail-level W

