name: CI

on: [push, pull_request]

jobs:
  el-tests:
    name: el${{ matrix.os-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-version: [7, 8, 9]
        include:
          - os-version: 7
            docker-image: centos:7
            ruby-package: ruby
          - os-version: 8
            docker-image: rockylinux:8
            ruby-package: ruby
          - os-version: 9
            docker-image: rockylinux:9
            ruby-package: ruby
    steps:
      - uses: actions/checkout@v4

      - name: Run tests in container
        run: |
          docker run --rm \
            -v $PWD:/workspace \
            -w /workspace \
            ${{ matrix.docker-image }} \
            bash -c "
              yum install -y ${{ matrix.ruby-package }} rubygems && \
              if [ ${{ matrix.os-version }} -eq 9 ]; then \
                yum module enable gcc-toolset -y; \
                yum groupinstall \"Development Tools\"; \
                yum install -y gcc gcc-c++ make ruby-devel; \
              fi && \
              ruby -v && \
              ruby -c check_pve.rb && \
              ruby check_pve.rb --help || echo 'Expected failure on very old Ruby is OK' && \
              if [ ${{ matrix.os-version }} -eq 9 ]; then \
                gem install rubocop && \
                find / -iname \"prism.h\"; \
                cat /usr/local/lib64/gems/ruby/prism-1.4.0/mkmf.log; \
                rubocop --fail-level W; \
              fi
            "

