name: CI

on: [push, pull_request]

jobs:
  el7:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:7
    steps:
      - name: Install tools
        run: |
          yum install -y centos-release-scl
          yum install -y gcc make which git ruby ruby-devel
          ruby --version
      - uses: actions/checkout@v4
      - name: Syntax check
        run: ruby -c check_pve.rb
      - name: Smoke test
        run: ruby check_pve.rb --help || echo "Expected failure on old Ruby is OK"

  el8:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
    steps:
      - name: Install tools
        run: |
          dnf install -y gcc make which git ruby ruby-devel
          ruby --version
      - uses: actions/checkout@v4
      - name: Syntax check
        run: ruby -c check_pve.rb
      - name: Smoke test
        run: ruby check_pve.rb --help
      - name: Lint
        run: |
          gem install rubocop
          rubocop --fail-level W

  el9:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    steps:
      - name: Install tools
        run: |
          dnf install -y ruby ruby-devel
          dnf groupinstall -y "Development Tools"
          ruby --version
      - uses: actions/checkout@v4
      - name: Syntax check
        run: ruby -c check_pve.rb
      - name: Smoke test
        run: ruby check_pve.rb --help
      - name: Lint
        run: |
          gem install rubocop
          rubocop --fail-level W

